### ISSUE TITLE
Error running: make prereqs

### ISSUE THREAD

**Issue by mkhooja** [Pinafore/qb#24]
It seems data/external/wikipedia is empty and is causing the following error when running make:

```
python3 cli.py build_mentions_lm_data data/external/wikipedia /tmp/wiki_sent

2016-06-30 01:46:06,946 - __main__ - INFO - QANTA starting with configuration:
2016-06-30 01:46:06,947 - __main__ - INFO - QB_SPARK_MASTER=localhost
2016-06-30 01:46:06,947 - __main__ - INFO - QB_API_USER_ID=1
2016-06-30 01:46:06,947 - __main__ - INFO - QB_GUESS_DB=/home/ubuntu/qb/output/guesses.db
2016-06-30 01:46:06,947 - __main__ - INFO - QB_API_KEY=
2016-06-30 01:46:06,947 - __main__ - INFO - QB_API_DOMAIN=
2016-06-30 01:46:06,947 - __main__ - INFO - QB_QUESTION_DB=/home/ubuntu/qb/data/internal/non_naqt.db
2016-06-30 01:46:06,948 - __main__ - INFO - QB_ROOT=/home/ubuntu/qb
2016-06-30 01:46:06,948 - __main__ - INFO - QB_WIKI_LOCATION=/home/ubuntu/qb/external/wikipedia
2016-06-30 01:46:06,948 - __main__ - INFO - QB_STREAMING_CORES=12
lmplz -o 5 < /tmp/wiki_sent > output/kenlm.arpa
=== 1/5 Counting and sorting n-grams ===
Reading /tmp/wiki_sent
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
Unigram tokens 0 types 3
=== 2/5 Calculating and sorting adjusted counts ===
Chain sizes: 1:36 2:1252070016 3:2347631360 4:3756210176 5:5477806592
/home/ubuntu/dependencies/kenlm/lm/builder/adjust_counts.cc:52 in void lm::builder::{anonymous}::StatCollector::CalculateDiscounts(const lm::builder::DiscountConfig&) threw BadDiscountException because `s.n[j] == 0'.
Could not calculate Kneser-Ney discounts for 1-grams with adjusted count 2 because we didn't observe any 1-grams with adjusted count 1; Is this small or artificial data?
Try deduplicating the input.  To override this error for e.g. a class-based model, rerun with --discount_fallback

Aborted (core dumped)
```

**Comment by EntilZha** [comment]
This is what I was last working on. Once I finish the scripts to do this, I will push up that change and post here.

More or less, the Wikifier data has to be downloaded and put in the correct place.

**Comment by mkhooja** [comment]
Great. Thanks!

**Comment by mkhooja** [comment]
When you refer to Wikifier data, where exactly can we download this data from?  the README file refers to : 
http://cogcomp.cs.illinois.edu/page/software_view/Wikifier
Which installs a .zip file.  Is the wikipedia data a subfolder in that file?  

Thanks,

**Comment by EntilZha** [comment]
Just recalled why that error is occurring (and how to fix it). While it is true that we need Wikifier, the source of the error above is that our Wikipedia cache hasn't been filled. I didn't notice this until now that I am starting from an empty repository since my cache had been filled for a while.

Its not the best thing, but `qanta.wikipedia.cached_wikipedia.CachedWikipedia` lets us query for a Wikipedia page. If it exists, then we use it otherwise we download it. The fix to make this exist is as simple as iterating over all the possible answers. I will also push this fix up with everything else.

**Comment by EntilZha** [comment]
Got that working. Once I am done there will be a make target, but I will also upload a copy of the data to Amazon S3. That should make it easy to either use the Makefile and wait or download the raw data and put it into the correct directory.

I also did the same with the Wikifier2013.zip since it takes quite a while to download from their website. Will update here and the docs once everything looks good to go

**Comment by mkhooja** [comment]
I did notice that CachedWikipedia tries to pickle.load the pages locally and download if not found. I wasn't sure where to get the list of keys(files).  

I ran into other minor issues while running make.  You can find details in the pull request (https://github.com/Pinafore/qb/pull/25)

**Comment by EntilZha** [comment]
This shows how to pull the keys from the questions database. https://github.com/Pinafore/qb/blob/master/qanta/wikipedia/cached_wikipedia.py#L87

**Comment by EntilZha** [comment]
I got things working through to just before training the deep guesser. The make targets are present and in `bin/bootstrap.sh` there are aws cli commands to download the larger files as well

**Comment by hpduong** [comment]
I have Wikifier2013.zip, but where/how can I download s3://pinafore/public/wikipedia.tar.gz?  I'm doing a local install on Xubuntu.

**Comment by hpduong** [comment]
How can I manually download the wikipedia.tar.gz file to my local Xubuntu system? 

I'm looking at the /bin/boostrap.sh file

```

aws s3 cp s3://pinafore/public/wikipedia.tar.gz /tmp/wikipedia.tar.gz
tar -xvzf /tmp/wikipedia.tar.gz -C data/external
rm /tmp/wikipedia.tar.gz
```

**Comment by EntilZha** [comment]
There are two ways:

1. There is a make target `data/external/wikipedia/` that will fill the appropriate directory. Since `CachedWikipedia` will attempt to fetch a missing article at access time, the target will iterate through all the pages. This takes a while (I think 1-2 hours) and most of it is because of request/response time delay.
2. To avoid having to do that (especially for Ansible scripts I am writing), I uploaded the filled wiki directory to `s3://pinafore/public/wikipedia.tar.gz`. To download that, steps are below:


## Download S3 Wikipedia dump (~300MB)
1. `pip install awscli`
2. `aws configure`, this requires AWS credentials
3. Look at https://github.com/Pinafore/qb/blob/master/bin/bootstrap.sh which has the appropriate commands to place the downloaded file in the correct place. Note that AWS will incur small transfer costs since data is outbound from AWS

I know there is a way to expose S3 buckets via https, but I won't be able to check that until I get to my personal computer later today after work

**Comment by EntilZha** [comment]
I double checked and there isn't a great way to make S3 buckets available via https since we would have to make the entire bucket public and also pay for outbound network transfer costs. End effect is either you would need to run the make target or download using `awscli` with AWS keys

**Comment by EntilZha** [comment]
Closing since this seems resolved.
