### ISSUE TITLE
Error running: luigi --module qanta.pipeline AllSummaries --workers 30

### ISSUE THREAD

**Issue by hpduong** [Pinafore/qb#28]
```
File "/usr/local/lib/python2.7/dist-packages/luigi/cmdline_parser.py", line 144, in _attempt_load_module
    __import__(module)
ImportError: No module named qanta.pipeline
```
Could someone point me in the right direction?

**Comment by EntilZha** [comment]
Need more information for me to be able to help you:

1. What setup commands have been run
2. What command are you running to run into this error
3. What directory are you running that command from

Based only on what you posted, it looks like you are using python 2.7 which is not compatible with qanta. To run the qb code you need at least python 3.4 since we make use of a new python features like type hinting. The error above is probably due to the fact that python 3 uses absolute imports and python 2 uses relative imports by default

**Comment by hpduong** [comment]
Thanks for the help.

I'm following the latest Readme.md.   
I've gone through
Dependencies
Installation
Env Variables
Prerequisites Heading

And then I started working on Batch Mode.

These instructions are a work in progress. Generally speaking, you need to start the spark cluster, start luigi, then submit the AllSummaries 

> task. If it is your first time running it, we suggest you use more intermediate targets from qanta/pipline.py
> 
> Start the spark cluster by navigating into $SPARK_HOME and running sbin/start-all.sh
> Start the Luigi daemon: luigid --background --address 0.0.0.0
> Run the pipeline: luigi --module qanta.pipeline AllSummaries --workers 30 (change 30 to number of concurrent tasks to run at a time)
> Observe pipeline progress at http://hostname:8082
> To rerun any part of the pipeline it is sufficient to delete the target file generated by the task you wish to rerun.

```
h@Xubuntu:~/qb$ python
Python 3.5.1 |Anaconda 4.1.0 (64-bit)| (default, Jun 15 2016, 15:32:45) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
h@Xubuntu:~/qb$ sudo luigi --module qanta.pipeline AllSummaries --workers 30
Traceback (most recent call last):
  File "/usr/local/bin/luigi", line 9, in <module>
    load_entry_point('luigi==2.1.1', 'console_scripts', 'luigi')()
  File "/usr/local/lib/python2.7/dist-packages/luigi/cmdline.py", line 10, in luigi_run
    run_with_retcodes(argv)
  File "/usr/local/lib/python2.7/dist-packages/luigi/retcodes.py", line 56, in run_with_retcodes
    with luigi.cmdline_parser.CmdlineParser.global_instance(argv):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/luigi/cmdline_parser.py", line 52, in global_instance
    new_value = CmdlineParser(cmdline_args)
  File "/usr/local/lib/python2.7/dist-packages/luigi/cmdline_parser.py", line 64, in __init__
    self._attempt_load_module(known_args)
  File "/usr/local/lib/python2.7/dist-packages/luigi/cmdline_parser.py", line 144, in _attempt_load_module
    __import__(module)
ImportError: No module named qanta.pipeline

```

**Comment by EntilZha** [comment]
The issue is: `sudo luigi ...`. If you look at the stack trace luigi is using python 2.7 since anaconda python is likely set as a path variable in your user's bashrc file. Is there a reason that you need to run the pipeline as sudo?

If so, you probably need to reference the python binary directly or do `sudo -E` to keep your environment

**Comment by hpduong** [comment]
No, don't need to run as sudo.  I get the same result either way. 

I also added 

`alias python=python3`

to my .bashrc.file. I don't know if that would even help but I got the same error. 

I had the same problem running sudo with -E.

**Comment by EntilZha** [comment]
Try doing `pip uninstall luigi` then `pip3 install luigi`. Luigi is probably installing into python 2.7 so it is using that instead of calling python 3

**Comment by hpduong** [comment]
Thanks! That helped get me through the Luigi issue. On to the next steps!
