### ISSUE TITLE
Error on Wikipedia.tar.gz download

### ISSUE THREAD

**Issue by hpduong** [Pinafore/qb#37]
For: 

`aws s3 cp s3://pinafore/public/wikipedia.tar.gz /tmp/wikipedia.tar.gz`

I'm getting this error:

ubuntu@ubuntu:~/qb$ aws s3 cp s3://pinafore/public/wikipedia.tar.gz /tmp/wikipedia.tar.gz

A client error (403) occurred when calling the HeadObject operation: Forbidden
Completed 1 part(s) with ... file(s) remaining

Is there any alternative way to obtain this file for a local install? I've tried to get it from an ec2 instance as well as using awscli locally with my security credentials entered with `awscli configure`.

**Comment by EntilZha** [comment]
Providing `wikipedia.tar.gz` is for convenience, it is technically not necessary. The file is the result of running `data/external/wikipedia/`. The reason we provide it is that this iterates over all possible answers and downloads the wiki page associated with it. This can take a while due to the request/response latency.

That being said, I will look into the permissions on our S3 bucket to make sure they are wide enough. I probably made the file public but not the public directory public is my guess

**Comment by EntilZha** [comment]
@hpduong gives the s3 cp another try, if that doesn't work I'll have to debug more

**Comment by hpduong** [comment]
Ah, great. The download is working now!

On Mon, Jul 11, 2016 at 12:04 PM, Pedro Rodriguez <notifications@github.com>
wrote:

> @hpduong <https://github.com/hpduong> gives the s3 cp another try, if
> that doesn't work I'll have to debug more
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Pinafore/qb/issues/37#issuecomment-231832447>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AEOhDTbM1l5ZIc6LPQuHv5aZCBjzaAhDks5qUpO2gaJpZM4JJqSU>
> .
>



--
