### ISSUE TITLE
look for wiki related files

### ISSUE THREAD

**Issue by henryzhao5852** [Pinafore/qb#63]
Hi, 

I want to run QANTA in a non-AWS way. Where can I find the file mentioned in the code "parsed-wiki.tar.lz4" and "wikidata-claims_instance-of.jsonl". Thanks!

Chen

**Comment by EntilZha** [comment]
Could you link the relevant code files? I believe those are saved in s3, but would need to move them over to our public repository. 

Those are actually processed from raw wikidata dumps which is in their website. As written the job that does that loads the dump into memory which is ~100gb and consumes >250gb of memory which is why the processed version exists.

**Comment by henryzhao5852** [comment]
it's in the preprocess.py at /qanta/pipeline directory
