### ISSUE TITLE
Training the Guesser via Luigi

### ISSUE THREAD

**Issue by ssanjiv** [Pinafore/qb#64]
From the __init__.py file in the guesser module of the qanta pipeline, there are TrainGuesser and GenerateGuesses tasks. My questions are as follows:

1) Could you please provide some documentation regarding the Luigi parameters for these tasks? Example usage would be helpful too.

2) Is there any way to save and load the model generated from TrainGuesser in order to reuse and prevent repetitive training in GenerateGuesses?

**Comment by EntilZha** [comment]
The workflow was designed so that you would:

1. Copy `qanta-defaults.hcl` to `qanta.hcl`
2. Modify any parameters as necessary
3. For testing a guesser run `AllSinglerGuesserReports` by executing `luigi --local-scheduler --module qanta.pipeline.guesser AllSingleGuesserReports`
4. If you are comparing guessers, use `AllGuesserReports` instead

Luigi can be thought of as a python version of `make`. When Those are run, it will check if for the configured guessers from `qanta.hcl` the reports generated from `GuesserReport` exist. If they don't, it will attempt to create them which depends on `GenerateGuesses`, which in turn depends on `TrainGuesser`. Once this has been run once, as with `make` no further work will be done since the outputs already exist so that should address (2).

The way that this work is that:
1. Guesser is trained, when that is completed it is persisted/saved/pickled to disk and the program exits. This uses `AbstractGuesser.train` and `AbstractGuesser.save`
2. When guesses are generated, the guesser will be loaded with `AbstractGuesser.load` then guesses are generated with `AbstractGuesser.guess`.

If you would like to load the guesser in a terminal session you can do `DANGuesser.load(guesser_dir)` where `guesser_dir` is something like `output/guesser/qanta.guesser.dan.DANGuesser`.

One thing to note about the elastic search guesser is that I never got around to implementing proper save/load so those methods will only work as expected if the machine on which it was trained is the same and the elastic search directory hasn't been modified/deleted.

**Comment by ezubaric** [comment]
I'm getting the following error

```
jbg@hongwu:~/repositories/qb> luigi --local-scheduler --module qanta.pipeline.guesser TrainGuesser
ERROR: Uncaught exception in luigi
Traceback (most recent call last):
  File "/home/jbg/anaconda3/lib/python3.6/site-packages/luigi/retcodes.py", line 74, in run_with_retcodes
    worker = luigi.interface._run(argv)['worker']
  File "/home/jbg/anaconda3/lib/python3.6/site-packages/luigi/interface.py", line 244, in _run
    return _schedule_and_run([cp.get_task_obj()], worker_scheduler_factory)
  File "/home/jbg/anaconda3/lib/python3.6/site-packages/luigi/cmdline_parser.py", line 116, in get_task_obj
    return self._get_task_cls()(**self._get_task_kwargs())
  File "/home/jbg/anaconda3/lib/python3.6/site-packages/luigi/task_register.py", line 88, in __call__
    param_values = cls.get_param_values(params, args, kwargs)
  File "/home/jbg/anaconda3/lib/python3.6/site-packages/luigi/task.py", line 411, in get_param_values
    raise parameter.MissingParameterException("%s: requires the '%s' parameter to be set" % (exc_desc, param_name))
luigi.parameter.MissingParameterException: TrainGuesser[args=(), kwargs={}]: requires the 'guesser_module' parameter to be set
```

I've copied qanta-defaults.hcl to qanta.hcl; where does guesser_module get set?

**Comment by ssanjiv** [comment]
I'm also getting an error in WikipediaRawRedirects() related to the s3 server.

```
ERROR: [pid 36871] Worker Worker(salt=463226959, workers=1, host=Shravan, username=ogg, pid=36871) failed    WikipediaRawRedirects()
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/luigi/worker.py", line 191, in run
    new_deps = self._run_get_new_deps()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/luigi/worker.py", line 129, in _run_get_new_deps
    task_gen = self.task.run()
  File "/Users/ogg/Programming/Test Project/qb_old/qanta/pipeline/preprocess.py", line 43, in run
    shell('aws s3 cp {} {}'.format(s3_location, ALL_WIKI_REDIRECTS))
  File "/Users/ogg/Programming/Test Project/qb_old/qanta/util/io.py", line 17, in shell
    return subprocess.run(command, check=True, shell=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'aws s3 cp s3://pinafore-us-west-2/public/wiki_redirects.csv data/external/wikipedia/all_wiki_redirects.csv' returned non-zero exit status 1.
```
I've tried running this from the command line directly:
```
Shravan:qb_old ogg$ aws s3 cp s3://pinafore-us-west-2/public/wiki_redirects.csv data/external/wikipedia/all_wiki_redirects.csv
fatal error: Unable to locate credentials
```

**Comment by ssanjiv** [comment]
@ezubaric 

If you're calling TrainGuesser from the command line, you'll have to manually pass in the parameters themselves. More specifically, if you take a look at the __init__.py (around line 28 in qanta/pipeline/guesser), here are the parameters that need to be set manually for TrainGuesser: 
```
    guesser_module = luigi.Parameter()  # type: str
    guesser_class = luigi.Parameter()  # type: str
    dependency_module = luigi.Parameter()  # type: str
    dependency_class = luigi.Parameter()  # type: str
```

However, calling AllSingleGuesserReports loads and sets these parameters using the qanta-defaults.hcl via the AbstractGuesser.list_enabled_guessers() class method. If you want to run TrainGuesser manually, I think the correct approach would be either calling AllSingleGuesserReports (which would also train other guessers) or passing in the parameters manually via the command line using these specifications (taken from the qanta-defaults.hcl):
```
guessers "ElasticSearch" {
  class = "qanta.guesser.elasticsearch.ElasticSearchGuesser"
  luigi_dependency = "qanta.pipeline.guesser.EmptyTask"
  enabled = true
  # Set the level of parallelism for guess generation
  n_cores = 15
  # Whether or not to index all Wikipedia articles for guessing
  use_all_wikipedia = false
  use_wiki = true
  use_qb = true
  use_source = false
  many_docs = false
  normalize_score_by_length = true
  wiki_boost = 1
  qb_boost = 1
}
```

Therefore, try this command: 
```
luigi --local-scheduler --module qanta.pipeline.guesser TrainGuesser --guesser-module qanta.guesser.elasticsearch --guesser-class ElasticSearchGuesser --dependency-module qanta.pipeline.guesser --dependency-class EmptyTask
```

**Comment by EntilZha** [comment]
@ssanjiv That seems like an authentication rather than authorization issue. This is a summary of how AWS/S3 works:

1. You acquire/configure AWS credentials, this is your access key id and secret access key. These need to be in your environment variables or in your aws dot files. The easiest way to make sure they are correct is running `aws configure`
2. We store files in S3, any file in `pinafore-us-west-2` is public. If you are accessing files from here there should be no permissions problems, you may run into problems if you are accessing internal buckets such as anything prefixed with `entilzha`
3. You access the file which requires: you are authenticated to AWS with your credentials, and that you are authorized to access the file/bucket in S3

The reason that you need to get credentials is that this is how AWS determines who should foot the bill for network transfer/bandwidth costs. In this case, it is to whoever's AWS credentials are used to authenticate to AWS.

One option @ezubaric may consider is making these files available via HTTP in which case our lab would foot any network costs.

Let me know if you still are running into issues.

@ssanjiv is correct on running the guessers. I haven't found the need to train a guesser without at the same time producing guesses/reports. If that is a common use case its not too much trouble to make a CLI/human friendly Luigi target.

**Comment by ssanjiv** [comment]
@EntilZha 

Thank you for all the help so far!

Could another option be eliminating the usage of Wiki data altogether? I understand this could entail loosing a lot of data, but what are your thoughts on the feasibility and functionality of taking this approach?

I think exploring this option would mean:
1) Deleting the relevant dependencies in the DownloadData task
2) Setting "use_wiki" to false in qanta-defaults

Is there anything else I'm missing?

**Comment by ezubaric** [comment]
Right, just a simple system, we just need the Wikipedia dump and nothing else.  Perhaps grab that by http directly from wikimedia and be done with it.

**Comment by EntilZha** [comment]
At least on the master branch, I prefer keeping Wiki enabled. The reason is that I think that the master branch should represent the project in its current state, and that the out of the box defaults should run the best current model (this is how it is right now). At the moment at least, I would be against any change on the master branch thats not aligned with this goal/philosophy.

Its easy enough to set `use_wiki=false` if you prefer not to deal with needing Wikipedia. For a simplified system I'll let @ezubaric decide what would be best to include/exclude since that is independent of what is on run by the qb pipeline in master.

With regards to dumps, it is easy to find the regular wikipedia dumps online. Getting `wiki_redirects.csv` requires quite a bit more work since they are the output of some of the Wikipedia SQL DB dumps. You can find instructions for how to do that here: https://github.com/Pinafore/qb#wikipedia-redirect-mapping-creation

**Comment by ssanjiv** [comment]
@EntilZha 

What is the functionality of `parsed-wiki.tar.lz4` as well as `wikidata-claims_instance-of.jsonl`, and how can I manually create these files?

**Comment by EntilZha** [comment]
You shouldn't need the wiki data file unless you are working on using wikidata.org data. That file takes a very long time to create unless you have access to a machine with 1-2TB of ram as well. 

If I recall parsed wiki is the result of running https://github.com/attardi/wikiextractor over the raw Wikipedia dumps. I would look at the lz4 file, but if I recall the JSON format flag is passed

**Comment by ssanjiv** [comment]
@EntilZha 

Jordan gave me the AWS keys, but the redirects.csv file gave me a 403 forbidden when trying to execute the command. Is the file still hosted on public/wiki_redirects.csv?

**Comment by ezubaric** [comment]
Note @ssanjiv shouldn't have any privleges to download; this is a good test of whether people can get things working correctly using public data.
