### ISSUE TITLE
It's done!

### ISSUE THREAD

**Issue by Rajan** [Pinafore/qb#8]
I've built the system as described. How do I test it?

**Comment by ezubaric** [comment]
That's actually not well documented at the moment.  If you want it to play quiz bowl, you can add an expo.csv file to the data directory (we'll add one ourselves after the Ken Jennings match) and then make "demo32", for example.

The expo file is a csv file like:

answer,text
Stroke,"One form of this condition can cause persistent hiccups in Wallenberg syndrome. When this condition affects the basilar system, it can cause locked-in syndrome. This condition is the leading cause of aphasias. The hemorrhagic type of this condition can be caused by hypertension, while ischemic types can cause one-sided paralysis. For 10 points—name this condition in which blood flow to the brain is interrupted."
Peter Pan,"This character is told that he will be fed to Mister Grin in a novel written by Ridley Pearson and Dave Barry, which depicts his encounter with the Starcatchers. In an earlier work, this character threatens Tootles with an arrow, and is driven out a window by the dog Nana. He teaches John, Michael, and Wendy Darling how to fly. For 10 points—name this boy created by J. M. Barrie, who lives in the Neverland."
Bavaria,"This state's northwestern region of Franconia is renowned for its wines. The Regen and Augsburg are cities in—for 10 points—what southern state of Germany governed from Munich?"
"Temperance Brennan","While this woman was at Burtonsville High, she befriended custodian Ray Buxley, who gave her dead animals to dissect. A computer genius named Christopher Pelant framed this woman for the murder of her schizophrenic friend Ethan Sawyer. She has a daughter named Christine with her partner, Seeley Booth. For 10 points—name this forensic anthropologist at the Jeffersonian, who is played by Emily Deschanel on a FOX series."
Haiti,"While serving as the first president of this country, Alexandre Petion led a successful slave revolt."
Gottfried Wilhelm Leibniz,"In this man's namesake harmonic triangle, each number equals the sum of the numbers beneath it. This mathematician's namesake series, 1 – 1/3 + 1/5 and so on, converges slowly to pi over 4. He used a stylized S to represent integrals and developed the notation dy over dx. to denote derivatives. For 10 points—name this German involved in a priority dispute with Isaac Newton over the invention of calculus. "
Coco Chanel,"In 1941 this designer attempted to undo an earlier agreement with the brothers Paul and Pierre Wertheimer 5. For 10 points—identify this French designer nicknamed Coco."
Stonewall riots,Dick Leitsch claimed that many of this event's participants were homeless runaways denied admission by The Sewer and The Snake Pit. The Daily News ran a story headed Queen Bees are Stinging Mad after this event, which began after a vice squad entered a Christopher Street bar and arrested those not wearing gender-appropriate clothing. For 10 points—name these 1969 riots considered the start of the gay rights movement.
Ecce homo,This phrase appears beside a stone doorway in a Hieronymus Bosch presents Jesus to the crowd emblazoned with—for 10 points—what two-word Latin phrase often translated as behold the man?
Electron,"Heteroatoms are often present in a variant of the Diels-Alder reaction named for an inverse demand of these species. These species were fired at a crystalline nickel target in the Davisson-Germer experiment. Transitions of these species in certain systems result in the Lyman series. A Lewis acid is defined as an entity that accepts a pair of—for 10 points—what elementary particles with a negative charge? "
Kate Chopin,"In one story by this author, Mrs. Sommers spends $15 on small luxuries. This author of A Pair of Silk Stockings also wrote about Louise, who whispers Body and soul free! after hearing that her husband Brently Mallard has died in The Story of an Hour. In a novel by this author, Léonce in The Awakening."
Ulysses S. Grant,"This president reprimanded his secretary of war, William W. Belknap, for opposing the construction of the Eads Bridge. Earlier in his administration, the Alabama Claims were settled by the Treaty of Washington, which was signed by his secretary of state, Hamilton Fish. His secretary, Orville Babcock, was implicated in the Whiskey Ring scandal. For 10 points—name this president who succeeded Andrew Johnson."
Theodore Gericault,"This artist created various portraits modeled after a shipwrecked Turk named Mustapha. In his final years, he created a series of paintings for Dr. Étienne Georget he displayed a work depicting an African waving a red cloth atop a barrel, along with 14 other shipwreck survivors. For 10 points—name this painter of The Raft of the Medusa."
Viscosity,"This quantity can generally be ignored in regions outside the boundary layer, but ignoring it completely gives rise to D'Alembert's equations. If inertial forces are much larger than the forces resulting from this property, then the Reynolds number is large. For 10 points—name this quantity that measures a fluid's resistance to flow. "

**Comment by EntilZha** [comment]
Is there anything else needed or close issue?

**Comment by Rajan** [comment]
Please close it. I'm travelling. Sorry.
